### ISSUE TITLE
UnboundLocalError: local variable 'rtime' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [saezlab/lipyd#1]
I installed your package using `pip install git+git://github.com/saezlab/lipyd.git`  and followed the instructions on the tutorial `https://saezlab.github.io/lipyd/lipyd_demo.html` and ran into the following problem:

`import imp  \
import itertools
import pprint
from lipyd import pprint_namedtuple
from lipyd import fragment
from lipyd import fragdb
from lipyd import *
from lipyd import mgf
from lipyd import settings
`

`
mgfreader= mgf.MgfReader("C:\\Users\\kunda\\HeLa_PASEF_pos_30min.mgf")  \
precursor = 590.45536  \ 
idx, rtdiff = mgfreader.lookup_scan-ids(precursor)`   \ 
and below is the first part of the output of the console

Line in MGF file `C:\Users\kunda\Documents\Computational-Lipidomics\Python\Kalman-and-Bayesian-Filters-in-Python\Bucket Table_HeLa_PASEF_pos_30min.mgf`could not be processed: 
	`POLARITY=POS `

Line in MGF file `C:\Users\kunda\Documents\Computational-Lipidomics\Python\Kalman-and-Bayesian-Filters-in-Python\Bucket Table_HeLa_PASEF_pos_30min.mgf`could not be processed: 
	`ION=[M+H]+`

And then this issue as well :

` Anaconda3\lib\site-packages\lipyd\mgf.py in __init__(self, fname, label, charge, rt_tolerance, drift, tolerance)
     60         self.rt_tolerance = rt_tolerance
     61         self.drift  = drift
---> 62         self.index()
     63         self.log = session.get_log()
     64         self.ms2_within_range = settings.get('ms2_within_range')  `
 
 ` Anaconda3\lib\site-packages\lipyd\mgf.py in index(self)
    158                         pepmass, # precursor ion mass
    159                         intensity, # intensity
--> 160                         rtime, # retention time
    161                         scan, # scan ID
    162                         offset, # byte offset in file `

` UnboundLocalError: local variable 'rtime' referenced before assignment `

Here is a link to where you can download the mgf file I am using for analysis:

https://syncandshare.lrz.de/getlink/fi8FibqmSbYp2ArSb21V3qiS/Bucket_Table_HeLa_PASEF_pos_30min_%281%29.mgf

**Comment by deeenes** [comment]
Hi Kundai,

Thanks a lot for your report, it's very useful for us to test this module with data from diverse sources, so we can adapt it to format variants.
With changes in 37142f0 I could read your MGF file.

Best wishes,

Denes
