### ISSUE TITLE
Issues building initial database

### ISSUE THREAD

**Issue by michaelmarty** [saezlab/lipyd#4]
Hi All,
I'm trying to get lipyd set up and it's crashing on the first import. The error I'm getting is:

File "C:\Python\lipyd\src\lipyd\mass.py", line 304, in setup_isotopes
    self.mass_monoiso[elem][nominal],
KeyError: 'H'

I tracked it a bit deeper, and I think the url_masses might have changed the way the website is built, and it's causing the reader to miss all the data on the website. The self.mass_monoiso has only the proton, neutron, and electron masses. No isotopes in there. I think there is a CSV that could probably be more easily read. Is there anything I'm missing here? Thanks,
MTM

**Comment by n-elie** [comment]
Hi,
I just encountered the same problem. Web archive shows that the website changed.
As a temporary workaround, I changed url to use archives (lipyd/mass.py, lines94 to 98):
```python
    #: URL for atomic masses
    url_masses = 'https://web.archive.org/web/20171003133929/http://www.ciaaw.org/atomic-masses.htm'
    #: URL for atomic weights
    url_weights = 'https://web.archive.org/web/20171003133929/http://www.ciaaw.org/atomic-weights.htm'
    #: URL for isotopic abundances
    url_abundances = 'https://web.archive.org/web/20171003133929/http://www.ciaaw.org/isotopic-abundances.htm'
```

**Comment by deeenes** [comment]
Thanks @n-elie, I've done just like you suggested
